import "./globals.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex flex-col items-center justify-between min-h-screen p-24 bg-gray-50 text-gray-900">
          {children}
        </main>
      </body>
     
    </html>
  )
}
